name: Build Minecraft PSP

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: pspdev/pspdev:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Toolchain
        run: |
          psp-config --version
          psp-gcc --version
          cmake --version
          make --version

      - name: Build
        run: |
          make

      - name: Show Build Output
        run: |
          ls -lah build
          find build -type f

      - name: Upload Build Folder
        uses: actions/upload-artifact@v4
        with:
          name: MinecraftPSP
          path: build/
