name: Build PSP

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: pspdev/pspdev:latest

    steps:
      - uses: actions/checkout@v4

      - name: Verify PSP SDK
        run: |
          psp-config --pspdev-path
          psp-config --pspsdk-path
      - name: Configure
        run: |
          cmake \
            -B build \
            -DCMAKE_TOOLCHAIN_FILE=.cmake/psp.cmake
      - name: Build
        run: |
          cmake --build build -j$(nproc)
      - name: Prepare Release
        run: |
          mkdir release
          cp build/EBOOT.PBP release/
          cp -r res release/
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MinecraftPSP
          path: release/
